### ISSUE TITLE
Cannot extend cart schema

### ISSUE THREAD

**Issue by karaarda** [reactioncommerce/api-plugin-carts#16]
In the transformAndValidateCart mutation the cart schema is loaded directly from file as `import { Cart as CartSchema } from "../simpleSchemas.js";`. It makes it impossible to extend the cart schema as the validation fails. The schema should be retrieved from the context as follows: `const CartSchema = context.simpleSchemas.Cart;`

**Comment by MohanNarayana** [comment]
All validation is done against simpleSchema. The same schema is available via context. Any change in schema that has to be validated should be added/updated to simpleSchema.js

**Comment by brent-hoover** [comment]
@MohanNarayana what @karaarda is referring to is that our code is using the version of the schema directly imported from the original definition, not the version that gets extended which is available via the context, therefore even when properly extended schema validation will fail. I think they properly suggest the fix there which is to change the validation in the cart code to use the extended schema via the context. This should be best practice everywhere.

**Comment by karaarda** [comment]
It does not matter for me anymore to be honest.

**Comment by brent-hoover** [comment]
Is that because you are no longer using Open Commerce? Or you found another solution?

**Comment by karaarda** [comment]
The one I shared in the original post is a valid solution I think.

After trying to find someone to get in touch for a year without luck and finding ourselves re-writing or overriding almost everything, reaction commerce costed us a lot.

**Comment by brent-hoover** [comment]
@karaarda Would you be willing to talk to me about your experiences? https://discord.gg/aqnvYFZc

**Comment by karaarda** [comment]
@zenweasel joined the discord server but couldn't find you. feel free to find me in the server and text me
