### ISSUE TITLE
Fix anonymousCartByCartId query. Make it accept cartId and anonymous access token.

### ISSUE THREAD

**Issue by MohanNarayana** [reactioncommerce/api-plugin-carts#33]
## Issue Description
Discussion in PR #30 

## Possible Solution
Remove OR condition in DB query. Handle case where anonymousAccessToken is sent hashed and not hashed.

**Comment by MohanNarayana** [comment]
The root issue for making and reverting these changes is #7. The product configuration is correctly retrieved if we use the cartId (anonymousCartId) and cartToken (anonymousCartToken) from the browser's Local storage. Using values from DB returns null. 
Changes made to this issue is based on discussion in PR #30

**Comment by brent-hoover** [comment]
Rather than reference a discussion in another thread and other tickets can you just provide a brief summary of the issue in the issue description and title? Also is that it needs to accept these or that it needs to **require** both?

**Comment by MohanNarayana** [comment]
@zenweasel Both the parameters are required for the query. Access token is not implemented.
