### ISSUE TITLE
ProductConfiguration not provided in anonymousCartByCartId query

### ISSUE THREAD

**Issue by bjanssen-pon** [reactioncommerce/api-plugin-carts#7]
Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
When I query the cart for the `productConfiguration` field, I get this error:
```
"message": "Cannot return null for non-nullable field CartItem.productConfiguration.",
      "locations": [
        {
          "line": 34,
          "column": 11
        }
      ],
      "path": [
        "anonymousCartByCartId",
        "checkout",
        "fulfillmentGroups",
        0,
        "items",
        0,
        "productConfiguration"
      ],
```

When checking the plugin, `productConfiguration` is based on `item.productId` and `item.variantId`. Both exist in the database on the `CartItem` object.

## Steps to Reproduce
1. Run the query `anonymousCartByCartIdQuery` in the playground for an anonymous cart.

## Possible Solution
Could be that the fields are not included in the item object when it's getting the data from the mongo collection.

### Versions
`3.7.1`

**Comment by delagroove** [comment]
closing due to bandwidth. feel free to open a PR with the fix in case you want to help out.

**Comment by MohanNarayana** [comment]
The query is currently returning null on the whole.
