### ISSUE TITLE
the possibility to choose several variants as in the case of a color and size variant

### ISSUE THREAD

**Issue by karbal** [reactioncommerce/api-plugin-carts#8]
If we take the example of a product with two variants color and size, therefore to add product in cart we must select a color in variant colors and a size in variant sizes.

With the structure of the cart we won't be able to do this kind of manipulation.

### My Solution
```json
{
  "Cart" : {
     ...
     products: ["productId":....,
"shopId":.....,
"addedAt":....,
"position": ....,
"quantity":.....,
         "items": []
     ]
  }
}
```
is to group the selection items of each catalog product.

**Comment by delagroove** [comment]
there's no problem states in this ticket. @karbal currently this is something that works now
